#!/bin/sh

# Set these paths appropriately

BIN="/Users/asdc/scripts/bin"
CMD="/Users/asdc/scripts/cmd"
LIB="/Users/asdc/scripts/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovenian.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
