#!/bin/sh

# Set these paths appropriately

BIN="/Users/asdc/scripts/bin"
CMD="/Users/asdc/scripts/cmd"
LIB="/Users/asdc/scripts/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/french-abbreviations
PARFILE=${LIB}/french.par

$TOKENIZER -f -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
